In [3]:
import funciones

# EXtracción de los conjuntos de datos

Data Internet

A continuación se realizara la extracion a travez de la API de ENACOM, correspondientes a la data nacional de accesos a internet fijo, banda ancha

In [2]:
url4= "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/TOTAL-NACIO-DE-ACCES-48866/data.csv/?auth_key=izIDjhitsUg8xNsiismBEDYpsisF2rwPxc2ZzRrb"
df_total_nacional_acces_internet= funciones.extraer_caonjunto(url4)
df_total_nacional_acces_internet.head()

    Año  Trimestre  Banda ancha fija  Dial up  Total        Periodo
0  2022          4                11       12     11   Oct-Dic 2022
1  2022          3                11       12     11  Jul-Sept 2022
2  2022          2                11       12     11   Abr-Jun 2022
3  2022          1                11       13     11   Ene-Mar 2022
4  2021          4                10       13     10   Oct-Dic 2021

Obtenemos el dataframe

Se procede a cargar el dataset, para luego la realización de su respectivo ETL

In [3]:
df_total_nacional_acces_internet.to_parquet("../Data/Internet/Nacional/nacional_acces_inter.parquet")

Se procede a la extracion del dataset, de penetracion por hogares de internet fijo a nivel nacional

In [4]:
url_acces_ba_bang_provin = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/BANDA-ANCHA-Y-BANDA-ANGOS/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_acces_provin_bandas = funciones.extraer_caonjunto(url_acces_ba_bang_provin)
df_acces_provin_bandas.head()

    Año  Trimestre        Provincia  Banda ancha fija  Dial up  Total
0  2022          4     Buenos Aires                 5      6.0      5
1  2022          4  Capital Federal                 2      2.0      2
2  2022          4        Catamarca                71      1.0     71
3  2022          4            Chaco               144      5.0    144
4  2022          4           Chubut               168    904.0    169

Cargamos el dataset

In [5]:
df_acces_provin_bandas.to_parquet("../Data/Internet/Provincia/acces_provin_bandas.parquet")

Acceso a internet por tecnologia en las diferentes provincias

In [6]:
url_tec_provin = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/ACCES-A-INTER-FIJO-POR/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_acces_tec_provin = funciones.extraer_caonjunto(url_tec_provin)
df_acces_tec_provin

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
0,2022,4,Buenos Aires,326.0,3.0,1.0,130.0,72.0,5.0
1,2022,4,Capital Federal,139.0,1.0,139.0,5.0,32.0,2.0
2,2022,4,Catamarca,9.0,11.0,47.0,1.0,2.0,71.0
3,2022,4,Chaco,25.0,61.0,47.0,8.0,3.0,144.0
4,2022,4,Chubut,45.0,74.0,10.0,31.0,9.0,169.0
...,...,...,...,...,...,...,...,...,...
860,2014,1,Santa Fe,323.0,174.0,3.0,6.0,644.0,507.0
861,2014,1,Santiago Del Estero,33.0,4.0,19.0,915.0,34.0,37.0
862,2014,1,Tierra Del Fuego,22.0,3.0,648.0,1.0,3.0,28.0
863,2014,1,Tucumán,130.0,83.0,121.0,13.0,98.0,130.0
864,*,Los datos provinciales no coinciden a nivel na...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Carga de datos

In [7]:
df_acces_tec_provin.to_parquet("../Data/Internet/Provincia/acces_tec_provin.parquet")

Se extrae el dataset, de velocidad media de baja por provincia

In [8]:
vel_med_donw_provin = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/VELOC-PROME-DE-BAJAD-DE/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_vel_med_donw_provin = funciones.extraer_caonjunto(vel_med_donw_provin)
df_vel_med_donw_provin

      Año  Trimestre            Provincia  Mbps (Media de bajada)
0    2022          4         Buenos Aires                 111.000
1    2022          4      Capital Federal                  18.286
2    2022          4            Catamarca                   8.333
3    2022          4                Chaco                  10.402
4    2022          4               Chubut                   1.592
..    ...        ...                  ...                     ...
859  2014          1           Santa Cruz                 332.000
860  2014          1             Santa Fe                 315.000
861  2014          1  Santiago Del Estero                 295.000
862  2014          1     Tierra Del Fuego                 345.000
863  2014          1              Tucumán                 321.000

[864 rows x 4 columns]

Carga de los datos

In [9]:
df_vel_med_donw_provin.to_parquet("../Data/Internet/Provincia/velo_medi_bajada.parquet")

Dataset de acceso a internet fijo por velocidad de bajada para localidades

In [10]:
acce_localidad = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/ACCES-A-INTER-FIJO-16249/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_acce_localidad = funciones.extraer_caonjunto(acce_localidad)
df_acce_localidad

,Provincia,Partido,Localidad,Link Indec,Otros,"0,256 Mbps","0,375 Mbps","0,5 Mbps","0,512 Mbps","0,625 Mbps",...,61 Mbps,62 Mbps,64 Mbps,65 Mbps,66 Mbps,70 Mbps,75 Mbps,78 Mbps,80 Mbps,83 Mbps
0,BUENOS AIRES,25 de Mayo,25 de Mayo,6854100,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN
1,BUENOS AIRES,25 de Mayo,Agustín Mosconi,6854010,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BUENOS AIRES,25 de Mayo,Del Valle,6854020,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BUENOS AIRES,25 de Mayo,Ernestina,6854030,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,6854040,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3090,TUCUMAN,Tafí Viejo,Villa Mariano Moreno - El Colmenar,90105100,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3091,TUCUMAN,Trancas,San Pedro de Colalao,90112020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3092,TUCUMAN,Trancas,Villa de Trancas,90112030,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3093,TUCUMAN,Yerba Buena,Villa Carmela,90119020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3094,TUCUMAN,Yerba Buena,Yerba Buena - Marcos Paz,90119030,176.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_acce_localidad.to_parquet("../Data/Internet/Localidad/acceso_localidad.parquet")

Acceso a internet por tecnologia y provincia

In [12]:
acc_tec_loc = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/ACCES-A-INTER-FIJO-62463/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_acc_tec_loc = funciones.extraer_caonjunto(acc_tec_loc)
df_acc_tec_loc

,Provincia,Partido,Localidad,Link Indec,ADSL,CABLEMODEM,DIAL UP,FIBRA OPTICA,OTROS,SATELITAL,WIMAX,WIRELESS,Total general,Unnamed: 13
0,BUENOS AIRES,25 de Mayo,25 de Mayo,6854100,874,"4,54",- 0,3,- 0,852,- 0,706,"6,98",NaN
1,BUENOS AIRES,25 de Mayo,Del Valle,6854020,181,- 0,- 0,- 0,10,1,- 0,- 0,192,NaN
2,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,6854040,- 0,- 0,- 0,- 0,- 0,- 0,- 0,181,181,NaN
3,BUENOS AIRES,25 de Mayo,Norberto de la Riestra,6854060,- 0,782,- 0,6,167,- 0,- 0,327,"1,28",NaN
4,BUENOS AIRES,25 de Mayo,Lucas Monteverde,6854050,- 0,- 0,- 0,- 0,- 0,- 0,- 0,6,6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3132,TUCUMAN,Tafí Viejo,Villa Mariano Moreno - El Colmenar,90105100,- 0,31,- 0,"3,73",- 0,- 0,- 0,- 0,"3,76",NaN
3133,TUCUMAN,Trancas,San Pedro de Colalao,90112020,- 0,- 0,- 0,- 0,- 0,- 0,- 0,313,313,NaN
3134,TUCUMAN,Trancas,Villa de Trancas,90112030,126,- 0,- 0,- 0,33,- 0,- 0,101,260,NaN
3135,TUCUMAN,Yerba Buena,Villa Carmela,90119020,"1,5",- 0,- 0,- 0,1,- 0,- 0,97,"1,6",NaN
3136,TUCUMAN,Yerba Buena,Yerba Buena - Marcos Paz,90119030,129,209,- 0,"15,4",33,- 0,- 0,- 0,"15,78",NaN

In [13]:
df_acc_tec_loc.to_parquet("../Data/Internet/Localidad/acceso_tecno_localidad.parquet")

Localidades con conectividad a internet

In [14]:
loc_conec_internet = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/LISTA-DE-LOCAL-CON-CONEC/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_loc_conec_internet = funciones.extraer_caonjunto(loc_conec_internet)
df_loc_conec_internet

,Provincia,Partido,Localidad,ADSL,Cablemódem,Dial Up,Fibra óptica,4G,3G,Telefonía Fija,Wireless,Satelital
0,BUENOS AIRES,9 de Julio,Alfredo Demarchi (Est. Facundo Quiroga),SI,--,--,--,SI,SI,SI,--,--
1,BUENOS AIRES,9 de Julio,Carlos María Naón,--,--,--,--,SI,SI,SI,--,--
2,BUENOS AIRES,9 de Julio,Dudignac,--,--,SI,--,SI,SI,SI,SI,--
3,BUENOS AIRES,9 de Julio,La Aurora (Est. La Niña),--,--,--,--,SI,--,--,--,--
4,BUENOS AIRES,9 de Julio,Manuel B. Gonnet (Est. French),SI,--,--,SI,SI,SI,SI,--,--
...,...,...,...,...,...,...,...,...,...,...,...,...
4306,BUENOS AIRES,Pilar,Pilar,SI,SI,SI,SI,SI,SI,SI,SI,SI
4307,BUENOS AIRES,Pilar,Presidente Derqui,SI,SI,--,SI,SI,SI,SI,SI,--
4308,BUENOS AIRES,Pilar,Roberto De Vicenzo,--,--,--,--,SI,SI,--,--,--
4309,BUENOS AIRES,Pilar,Santa Teresa,--,--,--,--,SI,SI,--,--,SI
4310,BUENOS AIRES,Pilar,Tortuguitas,--,--,--,SI,SI,SI,--,SI,SI

carga de dataset

In [15]:
df_loc_conec_internet.to_parquet("../Data/Internet/Localidad/localidades_conexion_internet.parquet")

Ingresos por la operacion de servicios de internet fijo

In [18]:
ingresos_internet = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/INGRE-POR-LA-OPERA-DEL/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_ingresos_internet = funciones.extraer_caonjunto(ingresos_internet)
df_ingresos_internet

     Año  Trimestre  Ingresos (miles de pesos)        Periodo
0   2022          4                         72   Oct-Dic 2022
1   2022          3                         64  Jul-Sept 2022
2   2022          2                         60   Abr-Jun 2022
3   2022          1                         55   Ene-Mar 2022
4   2021          4                         45   Oct-Dic 2021
5   2021          3                         43  Jul-Sept 2021
6   2021          2                         38   Abr-Jun 2021
7   2021          1                         37   Ene-Mar 2021
8   2020          4                         34   Oct-Dic 2020
9   2020          3                         32  Jul-Sept 2020
10  2020          2                         32   Abr-Jun 2020
11  2020          1                         30   Ene-Mar 2020
12  2019          4                         24   Oct-Dic 2019
13  2019          3                         22  Jul-Sept 2019
14  2019          2                         21   Abr-Jun 2019
15  2019          1                         20   Ene-Mar 2019
16  2018          4                         17   Oct-Dic 2018
17  2018          3                         15  Jul-Sept 2018
18  2018          2                         14   Abr-Jun 2018
19  2018          1                         13   Ene-Mar 2018
20  2017          4                         11   Oct-Dic 2017
21  2017          3                         10  Jul-Sept 2017
22  2017          2                         10   Abr-Jun 2017
23  2017          1                          9   Ene-Mar 2017
24  2016          4                          7   Oct-Dic 2016
25  2016          3                          7  Jul-Sept 2016
26  2016          2                          7   Abr-Jun 2016
27  2016          1                          6   Ene-Mar 2016
28  2015          4                          5   Oct-Dic 2015
29  2015          3                          5  Jul-Sept 2015
30  2015          2                          5   Abr-Jun 2015
31  2015          1                          5   Ene-Mar 2015
32  2014          4                          4   Oct-Dic 2014
33  2014          3                          3  Jul-Sept 2014
34  2014          2                          3   Abr-Jun 2014
35  2014          1                          3   Ene-Mar 2014

Cargar dataset

In [ ]:
df_ingresos_internet.to_parquet("../Data/Internet/Nacional/ingresos_operacion_internet.parquet")