In [2]:
import funciones

# EXtracción de los conjuntos de datos

Data Internet

A continuación se realizara la extracion a travez de la API de ENACOM, correspondientes a la data nacional de accesos a internet fijo, banda ancha

In [3]:
url4= "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/TOTAL-NACIO-DE-ACCES-48866/data.csv/?auth_key=izIDjhitsUg8xNsiismBEDYpsisF2rwPxc2ZzRrb"
df_total_nacional_acces_internet= funciones.extraer_caonjunto(url4)
df_total_nacional_acces_internet.head()

    Año  Trimestre  Banda ancha fija  Dial up  Total        Periodo
0  2022          4                11       12     11   Oct-Dic 2022
1  2022          3                11       12     11  Jul-Sept 2022
2  2022          2                11       12     11   Abr-Jun 2022
3  2022          1                11       13     11   Ene-Mar 2022
4  2021          4                10       13     10   Oct-Dic 2021

Obtenemos el dataframe

Se procede a cargar el dataset, para luego la realización de su respectivo ETL

In [4]:
df_total_nacional_acces_internet.to_parquet("../Data/Internet/Nacional/nacional_acces_inter.parquet")

Se procede a la extracion del dataset, de penetracion por hogares de internet fijo a nivel nacional

In [11]:
url_acces_ba_bang_provin = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/BANDA-ANCHA-Y-BANDA-ANGOS/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_acces_provin_bandas = funciones.extraer_caonjunto(url_acces_ba_bang_provin)
df_acces_provin_bandas.head()

    Año  Trimestre        Provincia  Banda ancha fija  Dial up  Total
0  2022          4     Buenos Aires                 5      6.0      5
1  2022          4  Capital Federal                 2      2.0      2
2  2022          4        Catamarca                71      1.0     71
3  2022          4            Chaco               144      5.0    144
4  2022          4           Chubut               168    904.0    169

Cargamos el dataset

In [14]:
df_acces_provin_bandas.to_parquet("../Data/Internet/Provincia/acces_provin_bandas.parquet")

Acceso a internet por tecnologia en las diferentes provincias

In [16]:
url_tec_provin = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/ACCES-A-INTER-FIJO-POR/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_acces_tec_provin = funciones.extraer_caonjunto(url_tec_provin)
df_acces_tec_provin

,Año,Trimestre,Provincia,ADSL,Cablemodem,Fibra óptica,Wireless,Otros,Total
0,2022,4,Buenos Aires,326.0,3.0,1.0,130.0,72.0,5.0
1,2022,4,Capital Federal,139.0,1.0,139.0,5.0,32.0,2.0
2,2022,4,Catamarca,9.0,11.0,47.0,1.0,2.0,71.0
3,2022,4,Chaco,25.0,61.0,47.0,8.0,3.0,144.0
4,2022,4,Chubut,45.0,74.0,10.0,31.0,9.0,169.0
...,...,...,...,...,...,...,...,...,...
860,2014,1,Santa Fe,323.0,174.0,3.0,6.0,644.0,507.0
861,2014,1,Santiago Del Estero,33.0,4.0,19.0,915.0,34.0,37.0
862,2014,1,Tierra Del Fuego,22.0,3.0,648.0,1.0,3.0,28.0
863,2014,1,Tucumán,130.0,83.0,121.0,13.0,98.0,130.0
864,*,Los datos provinciales no coinciden a nivel na...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Carga de datos

In [18]:
df_acces_tec_provin.to_parquet("../Data/Internet/Provincia/acces_tec_provin.parquet")

Se extrae el dataset, de velocidad media de baja por provincia

In [20]:
vel_med_donw_provin = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/VELOC-PROME-DE-BAJAD-DE/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_vel_med_donw_provin = funciones.extraer_caonjunto(vel_med_donw_provin)
df_vel_med_donw_provin

      Año  Trimestre            Provincia  Mbps (Media de bajada)
0    2022          4         Buenos Aires                 111.000
1    2022          4      Capital Federal                  18.286
2    2022          4            Catamarca                   8.333
3    2022          4                Chaco                  10.402
4    2022          4               Chubut                   1.592
..    ...        ...                  ...                     ...
859  2014          1           Santa Cruz                 332.000
860  2014          1             Santa Fe                 315.000
861  2014          1  Santiago Del Estero                 295.000
862  2014          1     Tierra Del Fuego                 345.000
863  2014          1              Tucumán                 321.000

[864 rows x 4 columns]

Carga de los datos

In [22]:
df_vel_med_donw_provin.to_parquet("../Data/Internet/Provincia/velo_medi_bajada.parquet")

Dataset de acceso a internet fijo por velocidad de bajada para localidades

In [23]:
acce_localidad = "http://api.datosabiertos.enacom.gob.ar/api/v2/datastreams/ACCES-A-INTER-FIJO-16249/data.csv/?auth_key=9cun92xcuW7JGFfRreeHvM0expDhKp0w8OXd7h6q"
df_acce_localidad = funciones.extraer_caonjunto(acce_localidad)
df_acce_localidad

,Provincia,Partido,Localidad,Link Indec,Otros,"0,256 Mbps","0,375 Mbps","0,5 Mbps","0,512 Mbps","0,625 Mbps",...,61 Mbps,62 Mbps,64 Mbps,65 Mbps,66 Mbps,70 Mbps,75 Mbps,78 Mbps,80 Mbps,83 Mbps
0,BUENOS AIRES,25 de Mayo,25 de Mayo,6854100,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN
1,BUENOS AIRES,25 de Mayo,Agustín Mosconi,6854010,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BUENOS AIRES,25 de Mayo,Del Valle,6854020,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BUENOS AIRES,25 de Mayo,Ernestina,6854030,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BUENOS AIRES,25 de Mayo,Gobernador Ugarte,6854040,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3090,TUCUMAN,Tafí Viejo,Villa Mariano Moreno - El Colmenar,90105100,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3091,TUCUMAN,Trancas,San Pedro de Colalao,90112020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3092,TUCUMAN,Trancas,Villa de Trancas,90112030,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3093,TUCUMAN,Yerba Buena,Villa Carmela,90119020,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3094,TUCUMAN,Yerba Buena,Yerba Buena - Marcos Paz,90119030,176.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_acce_localidad.to_parquet("../Data/Internet/Localidad/acceso_localidad.parquet")